# With some help from: https://gist.github.com/dgerosa/2e1f47a39180f39bde848e38243efa94

name: build
permissions:
  contents: read
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: .
      FILE: cv
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v5
      - name: Install TeX Live
        uses: zauguin/install-texlive@v4
        with:
          package_file: tl_packages
      - name: Compile cv
        id: build
        run: latexmk -pdflua -lualatex="lualatex --shell-escape %O %S" -interaction=nonstopmode -output-directory=${{ env.DIR }} ${{ env.DIR }}/${{ env.FILE }}.tex
      - name: Copy pdf to artifact folder
        run: mkdir -p github_artifacts && cp -v ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/
      - name: Add site files to artifact (index.html, CNAME)
        run: |
          mkdir -p github_artifacts
          # copy only if present (no failure if missing)
          for f in ${{ env.DIR }}/dist/index.html ${{ env.DIR }}/src/CNAME ${{ env.DIR }}/src/.nojekyll; do
            if [ -f "$f" ]; then
              cp -v "$f" github_artifacts/
            fi
          done
      - name: Upload pdf and site files for Github Pages
        id: deploy
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./github_artifacts
      - name: Move pdf to dist folder for Cloudflare Pages
        run: |
          mkdir -p ${{ env.DIR }}/dist
          mv -v ${{ env.DIR }}/${{ env.FILE }}.pdf ${{ env.DIR }}/dist/
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-GitHub:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    # Deploy to the github-pages environment
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
